apiVersion: v1
kind: ConfigMap
metadata:
  name: zenko
  namespace: zenko
data:
  SCALITY_ACCESS_KEY_ID: l11
  SCALITY_SECRET_ACCESS_KEY: l11
  S3BACKEND: file
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zenko
  name: zenko
  namespace: zenko
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zenko
  template:
    metadata:
      labels:
        app: zenko
    spec:
      nodeName: k8s-master
      containers:
      - name: zenko
        image: scality/s3server:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: zenko
        volumeMounts:
        - mountPath: /usr/src/app/localData
          name: local-data
        - mountPath: /usr/src/app/localMetadata
          name: local-metadata
        ports:
        - containerPort: 8000
        resources:
            limits:
              memory: "512Mi"
              cpu: "200m"
            requests:
              memory: "256Mi"
              cpu: "100m"
      volumes:
        - name: local-data
          hostPath:
            path: /mnt/zenko/app/localData
        - name: local-metadata
          hostPath:
            path: /mnt/zenko/app/localMetadata
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zenko
  name: zenko
  namespace: zenko
spec:
  type: NodePort
  selector:
    app: zenko
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    nodePort: 31541